worker_name = "worker1"
work_dir = "."
random_seed = 0
operation_mode = "Simulated"
[[radios]]
[radio_short]
broadcast_groups = ["group1"]
reliability = 1.0
delay = 0
interface_name = "wlan0"
[radio_long]
broadcast_groups = ["group1"]
reliability = 1.0
delay = 0
interface_name = "wlan0"
